/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BooksRouteImport } from './routes/books'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as GiveRouteImport } from './routes/give'
import { Route as LivestreamRouteImport } from './routes/livestream'
import { Route as MembershipRouteImport } from './routes/membership'
import { Route as MinistriesRouteImport } from './routes/ministries'
import { Route as PrayerRequestRouteImport } from './routes/prayer-request'
import { Route as SalvationRouteImport } from './routes/salvation'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as DevotionalIndexRouteImport } from './routes/devotional.index'
import { Route as DevotionalDateRouteImport } from './routes/devotional.$date'
import { Route as EventsIndexRouteImport } from './routes/events.index'
import { Route as EventsSlugRouteImport } from './routes/events.$slug'
import { Route as TeachingsIndexRouteImport } from './routes/teachings.index'
import { Route as TeachingsSeriesRouteImport } from './routes/teachings.$series'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksRoute = BooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const GiveRoute = GiveRouteImport.update({
  id: '/give',
  path: '/give',
  getParentRoute: () => rootRouteImport,
} as any)
const LivestreamRoute = LivestreamRouteImport.update({
  id: '/livestream',
  path: '/livestream',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipRoute = MembershipRouteImport.update({
  id: '/membership',
  path: '/membership',
  getParentRoute: () => rootRouteImport,
} as any)
const MinistriesRoute = MinistriesRouteImport.update({
  id: '/ministries',
  path: '/ministries',
  getParentRoute: () => rootRouteImport,
} as any)
const PrayerRequestRoute = PrayerRequestRouteImport.update({
  id: '/prayer-request',
  path: '/prayer-request',
  getParentRoute: () => rootRouteImport,
} as any)
const SalvationRoute = SalvationRouteImport.update({
  id: '/salvation',
  path: '/salvation',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DevotionalIndexRoute = DevotionalIndexRouteImport.update({
  id: '/devotional/',
  path: '/devotional/',
  getParentRoute: () => rootRouteImport,
} as any)
const DevotionalDateRoute = DevotionalDateRouteImport.update({
  id: '/devotional/$date',
  path: '/devotional/$date',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsSlugRoute = EventsSlugRouteImport.update({
  id: '/events/$slug',
  path: '/events/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TeachingsIndexRoute = TeachingsIndexRouteImport.update({
  id: '/teachings/',
  path: '/teachings/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeachingsSeriesRoute = TeachingsSeriesRouteImport.update({
  id: '/teachings/$series',
  path: '/teachings/$series',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/books': typeof BooksRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/give': typeof GiveRoute
  '/livestream': typeof LivestreamRoute
  '/membership': typeof MembershipRoute
  '/ministries': typeof MinistriesRoute
  '/prayer-request': typeof PrayerRequestRoute
  '/salvation': typeof SalvationRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/devotional/$date': typeof DevotionalDateRoute
  '/events/$slug': typeof EventsSlugRoute
  '/teachings/$series': typeof TeachingsSeriesRoute
  '/blog/': typeof BlogIndexRoute
  '/devotional/': typeof DevotionalIndexRoute
  '/events/': typeof EventsIndexRoute
  '/teachings/': typeof TeachingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/books': typeof BooksRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/give': typeof GiveRoute
  '/livestream': typeof LivestreamRoute
  '/membership': typeof MembershipRoute
  '/ministries': typeof MinistriesRoute
  '/prayer-request': typeof PrayerRequestRoute
  '/salvation': typeof SalvationRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/devotional/$date': typeof DevotionalDateRoute
  '/events/$slug': typeof EventsSlugRoute
  '/teachings/$series': typeof TeachingsSeriesRoute
  '/blog': typeof BlogIndexRoute
  '/devotional': typeof DevotionalIndexRoute
  '/events': typeof EventsIndexRoute
  '/teachings': typeof TeachingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/books': typeof BooksRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/give': typeof GiveRoute
  '/livestream': typeof LivestreamRoute
  '/membership': typeof MembershipRoute
  '/ministries': typeof MinistriesRoute
  '/prayer-request': typeof PrayerRequestRoute
  '/salvation': typeof SalvationRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/devotional/$date': typeof DevotionalDateRoute
  '/events/$slug': typeof EventsSlugRoute
  '/teachings/$series': typeof TeachingsSeriesRoute
  '/blog/': typeof BlogIndexRoute
  '/devotional/': typeof DevotionalIndexRoute
  '/events/': typeof EventsIndexRoute
  '/teachings/': typeof TeachingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/books'
    | '/contact'
    | '/dashboard'
    | '/give'
    | '/livestream'
    | '/membership'
    | '/ministries'
    | '/prayer-request'
    | '/salvation'
    | '/blog/$slug'
    | '/devotional/$date'
    | '/events/$slug'
    | '/teachings/$series'
    | '/blog/'
    | '/devotional/'
    | '/events/'
    | '/teachings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/books'
    | '/contact'
    | '/dashboard'
    | '/give'
    | '/livestream'
    | '/membership'
    | '/ministries'
    | '/prayer-request'
    | '/salvation'
    | '/blog/$slug'
    | '/devotional/$date'
    | '/events/$slug'
    | '/teachings/$series'
    | '/blog'
    | '/devotional'
    | '/events'
    | '/teachings'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/books'
    | '/contact'
    | '/dashboard'
    | '/give'
    | '/livestream'
    | '/membership'
    | '/ministries'
    | '/prayer-request'
    | '/salvation'
    | '/blog/$slug'
    | '/devotional/$date'
    | '/events/$slug'
    | '/teachings/$series'
    | '/blog/'
    | '/devotional/'
    | '/events/'
    | '/teachings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BooksRoute: typeof BooksRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  GiveRoute: typeof GiveRoute
  LivestreamRoute: typeof LivestreamRoute
  MembershipRoute: typeof MembershipRoute
  MinistriesRoute: typeof MinistriesRoute
  PrayerRequestRoute: typeof PrayerRequestRoute
  SalvationRoute: typeof SalvationRoute
  BlogSlugRoute: typeof BlogSlugRoute
  DevotionalDateRoute: typeof DevotionalDateRoute
  EventsSlugRoute: typeof EventsSlugRoute
  TeachingsSeriesRoute: typeof TeachingsSeriesRoute
  BlogIndexRoute: typeof BlogIndexRoute
  DevotionalIndexRoute: typeof DevotionalIndexRoute
  EventsIndexRoute: typeof EventsIndexRoute
  TeachingsIndexRoute: typeof TeachingsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books': {
      id: '/books'
      path: '/books'
      fullPath: '/books'
      preLoaderRoute: typeof BooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/give': {
      id: '/give'
      path: '/give'
      fullPath: '/give'
      preLoaderRoute: typeof GiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/livestream': {
      id: '/livestream'
      path: '/livestream'
      fullPath: '/livestream'
      preLoaderRoute: typeof LivestreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membership': {
      id: '/membership'
      path: '/membership'
      fullPath: '/membership'
      preLoaderRoute: typeof MembershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ministries': {
      id: '/ministries'
      path: '/ministries'
      fullPath: '/ministries'
      preLoaderRoute: typeof MinistriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prayer-request': {
      id: '/prayer-request'
      path: '/prayer-request'
      fullPath: '/prayer-request'
      preLoaderRoute: typeof PrayerRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salvation': {
      id: '/salvation'
      path: '/salvation'
      fullPath: '/salvation'
      preLoaderRoute: typeof SalvationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devotional/': {
      id: '/devotional/'
      path: '/devotional'
      fullPath: '/devotional/'
      preLoaderRoute: typeof DevotionalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devotional/$date': {
      id: '/devotional/$date'
      path: '/devotional/$date'
      fullPath: '/devotional/$date'
      preLoaderRoute: typeof DevotionalDateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$slug': {
      id: '/events/$slug'
      path: '/events/$slug'
      fullPath: '/events/$slug'
      preLoaderRoute: typeof EventsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teachings/': {
      id: '/teachings/'
      path: '/teachings'
      fullPath: '/teachings/'
      preLoaderRoute: typeof TeachingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teachings/$series': {
      id: '/teachings/$series'
      path: '/teachings/$series'
      fullPath: '/teachings/$series'
      preLoaderRoute: typeof TeachingsSeriesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BooksRoute: BooksRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  GiveRoute: GiveRoute,
  LivestreamRoute: LivestreamRoute,
  MembershipRoute: MembershipRoute,
  MinistriesRoute: MinistriesRoute,
  PrayerRequestRoute: PrayerRequestRoute,
  SalvationRoute: SalvationRoute,
  BlogSlugRoute: BlogSlugRoute,
  DevotionalDateRoute: DevotionalDateRoute,
  EventsSlugRoute: EventsSlugRoute,
  TeachingsSeriesRoute: TeachingsSeriesRoute,
  BlogIndexRoute: BlogIndexRoute,
  DevotionalIndexRoute: DevotionalIndexRoute,
  EventsIndexRoute: EventsIndexRoute,
  TeachingsIndexRoute: TeachingsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
